### PR TITLE
Problem: non-null foreign keys typing in GraphQL

### LINKED ISSUE #373: Non-null foreign-key doesn't result in a non-nullable graphQL field
**Describe the bug**
If a have a non-null foreign key on a "EmailAddress" table, let's say `accountId` that relates to the "id" column of an `Account` table, my `account` graphQL field  on my "EmailAddress" type will be nullable.

**To Reproduce**
The exact example of the doc doesn't produce the same schema for me (the "Relationships" part of the docs). It doesn't use a foreign key here but the docs states that it's the same.
This is the SQL statement in the example:
```sql
create table "Account"(
  id serial primary key,
  name text not null
);

create table "EmailAddress"(
  id serial primary key,
  "accountId" int not null, -- note: no foreign key
  "isPrimary" bool not null,
  address text not null
);

comment on table "EmailAddress" is e'
    @graphql({
        "foreign_keys": [
          {
            "local_name": "addresses",
            "local_columns": ["accountId"],
            "foreign_name": "account",
            "foreign_schema": "public",
            "foreign_table": "Account",
            "foreign_columns": ["id"]
          }
        ]
    })';
```

In the docs it says the resulting types are:
```graphql
type Account {
  nodeId: ID!
  id: Int!
  name: String!
  addresses(
    after: Cursor,
    before: Cursor,
    filter: EmailAddressFilter,
    first: Int,
    last: Int,
    orderBy: [EmailAddressOrderBy!]
  ): EmailAddressConnection
}

type EmailAddress {
  nodeId: ID!
  id: Int!
  isPrimary: Boolean!
  address: String!
  accountId: Int!
  account: Account!
}
```

Whereas for me this is what I get for the `EmailAddresses` type:
```graphql
type EmailAddress implements Node {
  nodeId: ID!
  id: Int!
  accountId: Int!
  isPrimary: Boolean!
  address: String!
  account: Account
}
```

You can see that for me `account` is nullable, whereas in the example it is not.

**Expected behavior**
I would expect that the `account` field to be of type `Account!` and not `Account`

**Versions:**
 - PostgreSQL: PostgreSQL 15.1 
 - pg_graphql commit ref: I'm using the pg_graphql extension of supabase, can't find the version it uses.

**Additional context**
I might be missing something really basic here since I'm not able to make the api docs example work correctly but I really don't know what it could be.

### PR DESCRIPTION
**Pull request by yrashk**
As per #373:

If a have a non-null foreign key on a "EmailAddress" table, let's say accountId that relates to the "id" column of an Account table, my account graphQL field on my "EmailAddress" type will be nullable.

Solution: take foreign key columns nullability into account

Resolves #373

---

## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

Current behavior matches pre 0.5 pg_graphql that does not take foreign key column nullability into account. See #373 

## What is the new behavior?

Take nullability into the account.

### CODE REVIEW

File: test/sql/issue_373.sql [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+            "foreign_keys": [
+              {
+                "local_name": "addresses",
+                "local_columns": ["accountId"],
+                "foreign_name": "account",
+                "foreign_schema": "public",
+                "foreign_table": "Account",
+                "foreign_columns": ["id"]
+              }
+            ]
```
Comment (olirice) [inline test/sql/issue_373.sql:26]: nit:
While the user in issue 373 is using a comment directive to define the foreign key, that is not material to the issue and could be confusing. Could you swap this out for a native key?

**Review by olirice — APPROVED** [review]
this looks great, thanks!

I'll make the nit change and get it merged

**Review by olirice — APPROVED** [review]
