### PR TITLE
Functions returning view type must have pkey (et.al.)

### LINKED ISSUE #481: Function returns set-of view fails introspection if view does not define primary key
**Describe the bug**
I reported this possible bug in the main supabase repository, but I believe it could be linked here.

https://github.com/supabase/supabase/issues/20106

> I followed the template for issues in that repository

### PR DESCRIPTION
**Pull request by olirice**
When a function returns a view's type and that view is `selectable` but does not have a primary key (a requirement to be present in the schema), the function contains an invalid type reference. This PR resolves that issue by requiring that all the requirements for a table/view to be included in the __Schema are met before allowing it to be returned by a function in the __Schema

This is another attempt at #477 which mirrors the logic in __Schema exactly rather than checking a subset of requirements.

The intended goal is to avoid invalid references caused by functions returning types that aren't present in the schema.

--------
Resolves #481

### CODE REVIEW

File: test/sql/function_calls.sql [hunk 1]
```diff
@@ -807,7 +807,7 @@ begin;
     rollback to savepoint a;
 
     create table account(
-        id int,
+        id int primary key,
```
Comment (olirice) [inline test/sql/function_calls.sql:810]: I had to add this to make the test valid since we require primary keys

File: test/sql/function_calls.sql [hunk 2]
```diff
@@ -820,21 +820,15 @@ begin;
...
-
     create function returns_null_account()
         returns account language sql stable
     as $$ select id, email, name from account where id = 9; $$;
 
     insert into account(id, email, name)
     values
         (1, 'aardvark@x.com', 'aardvark'),--all columns non-null
-        (2, 'bat@x.com', null),--mixed: some null, some non-null
-        (null, null, null);--all columns null
```
Comment (olirice) [inline test/sql/function_calls.sql:835]: after adding the pkey constraint, this record is no longer valid.

Since require a pkey I don't think it's necessary/possible to test for this case because can't happen. right?

**Review by imor — APPROVED** [review]
