### PR TITLE
Problem: Postgres enum value validity rules

### LINKED ISSUE #172: Support name overrides for enum variants
If a postgres enum variant is not a valid graphql `name`, loading the schema results in

```json
{
    "errors": [
        {"message": "Names must only contain [_a-zA-z0-9 but <invalid name> does not"}
    ]
}
```

for example, any enum variant containing a space will fail

### PR DESCRIPTION
**Pull request by yrashk**
They are wider than those for GraphQL as mentioned in #172.

Solution: allow specifying name mapping for enums via comments

Creating a comment like:

```sql
comment on type my_enum is E'@graphql({"mappings": {"valid value": "valid_value"}})';
```

Allows to override Postgres enum value to have a different value.

Please note that this is the first go at the problem, and it doesn't handle the following (and probably more):

* [ ] verification of new value's validity
* [x] mutations
* [ ] more exhaustive testing

Also, it is important to mention that while this approach does not implement a dynamic mapping technique proposed in #172 for the sake of conformity to the current approach used throughout pg_graphsql, it does not mean this will not or should happen in the future. A breaking release may indeed consider such a change for a variety of reasons:

* performance optimizations (mapping functions can be declared immutable)
* cases where comments aren't feasible or too onerous

Of particular note is an idea to dispatch conversions back to Postgres using an `inout` parameter to help us type on the return type.

---

## What kind of change does this PR introduce?

Workaround for specification compliance.

## What is the current behavior?

Using Postgres enum values as is. GraphQL has stricter rules for these. See #172 

## What is the new behavior?

Allowing overriding Postgres enum values.

## Additional context

resolves #172

### CODE REVIEW

File: sql/load_sql_context.sql [hunk 1]
```diff
@@ -359,7 +360,8 @@ select
                                                 select
                                                     jsonb_build_object(
                                                         'name', d.directive ->> 'name',
-                                                        'description', d.directive -> 'description'
+                                                        'description', d.directive -> 'description',
+                                                        'mappings', (graphql.comment_directive(pg_catalog.obj_description(pa.atttypid, 'pg_type'))) -> 'mappings'
```
Comment (olirice) [inline sql/load_sql_context.sql:364]: Let's look up mappings for columns as needed by traversing the SQL context in rust

I'd like to keep the SQL context free of all duplication

File: src/sql_types.rs [hunk 2]
```diff
@@ -21,6 +22,7 @@ pub struct ColumnPermissions {
 pub struct ColumnDirectives {
     pub name: Option<String>,
     pub description: Option<String>,
+    pub mappings: Option<BiBTreeMap<String, String>>,
```
Comment (olirice) [inline src/sql_types.rs:25]: which allows this to be removed

Comment (yrashk) [reply src/sql_types.rs:25]: My main concern here is that this way, `Column` would need to contain a reference to Schema and we'd do a (slower) traversal _each time_ we prepare the query.

Alternatively, this mapping information can be added to `Column` after the context is loaded by traversing the schema, but the outcome of this would be virtually indistinguishable from loading it from the SQL, and it still adds a one-time penalty for the resolution.

To me, it looked like a bit of duplication in the contexts is essentially faster and requires no significant type changes. Unless I am missing something?

File: sql/load_sql_context.sql (hunk 1 above)
Comment (yrashk) [reply sql/load_sql_context.sql:364]: See the comment below

File: src/sql_types.rs (hunk 2 above)
Comment (olirice) [reply src/sql_types.rs:25]: Yeah that is an issue but duplication in the SQL context has been a headache in the past because it's hard to track down everywhere that an update needs to be made.

For example, when user defined functions are introduced, we'll need the enum mappings for that too and would have to re-duplicate.

How about wrapping

```rust
pub struct ColumnBuilder {
  ...
  pub column: Arc<Column>
}
```
with an rust enum such that this is always `Arc<Column>, Arc<Type>` or `Arc<Column>, Arc<Enum>`?

---
During schema introspection and parsing user input the `Enum` is available so those are less of an issue

Comment (yrashk) [reply src/sql_types.rs:25]: It feels wrong to do this for ColumnBuilder as it is not very different from the SQL context population: sticking in data where it is used, not at the SQL query time but upon context loading. What if we need to have type information somewhere else? Should we augment those types as well? It'll get messy quickly, and your concern about duplication in the SQL context will hold just one level above.

To address this problem properly, we may need to review how context is loaded. For example, what if instead of storing `type_oid` as `u32` across the code base and if we refactor `Type`/`TypeCategory` to contain a reference to the actual type (`Arc<Enum>`, `Arc<Composite>`, etc.), then at any point, we can look up the type.

However, this is a much bigger change than the intended scope of the problem in this PR. What if we put a `TODO` kind of note in the SQL context concerning the duplication and the link to this discussion, get this merged (so that the users can benefit from the fix) and then work on a bigger refactoring?  Happy to discuss its details.

Comment (yrashk) [reply src/sql_types.rs:26]: I've added TODOs with links to this discussion.

**Review by olirice — APPROVED** [review]
