### PR TITLE
bugfix: arguments with null default were required

### LINKED ISSUE #507: UDF nullable arguments not being translated properly
**Describe the bug**
Since the changes in 1.4.3 (only recently deployed to supabase), I can't get optional function arguments working properly which we use pretty heavily.
Before this we simply had a postgres function signature with no defaults and each argument was implicitly nullable. Not supporting nullable UUID parameter types in UDF is a pretty major issue for us.

**To Reproduce**
1. Create a postgres function with a signature like this:
```sql
CREATE OR REPLACE FUNCTION public.convert_lead_into_work_order(lead_id_param uuid, scope_param text, assignee_id_param uuid DEFAULT NULL, client_reference_param text DEFAULT NULL)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$
```
2. Check signature in pg_graphql schema.

**Expected behavior**
I'd expect the GraphQL signature to look like this:
```graphql
convertLeadIntoWorkOrder(
    leadIdParam: UUID!
    scopeParam: String!
    assigneeIdParam: UUID
    clientReferenceParam: String
): UUID
```
Instead, I get this signature: (note the postgres NULL is translated into a string for `clientReferenceParam`, and the `assigneeIdParam` is still required).
```graphql
convertLeadIntoWorkOrder(
    leadIdParam: UUID!
    scopeParam: String!
    assigneeIdParam: UUID!
    clientReferenceParam: String = "NULL"
): UUID
```

---

I have also tried to set default client reference param to an empty string and default assignee ID param to a specify UUID in the UDF, however the UUID parameter in pg_graphql is still required.

**Versions:**
 - PostgreSQL: 15.1.1.33
 - pg_graphql commit ref: Supabase-hosted v1.5.1

**Additional context**
Please advise if there's a known workaround to get nullable UUID parameter types working again in UDFs.

### PR DESCRIPTION
**Pull request by imor**
## What kind of change does this PR introduce?

Bug fix

## What is the current behavior?

UDF args with a default value of null were either required or had a default value of "NULL" in case of string.

## What is the new behavior?

UDF args with a null default value will be optional.

## Additional context

Fixes #507

### CODE REVIEW

File: src/sql_types.rs [hunk 1]
```diff
@@ -88,7 +88,7 @@ pub struct Function {
 }
 
 impl Function {
-    pub fn args(&self) -> impl Iterator<Item = (u32, &str, Option<&str>, Option<String>)> {
+    pub fn args(&self) -> impl Iterator<Item = (u32, &str, Option<&str>, Option<(String, bool)>)> {
```
Comment (olirice) [inline src/sql_types.rs:91]: Could you pls create a struct for this so the values have associated names? It took me a while to figure out exactly what the bool represented
```
Option<(String, bool)
```

File: src/sql_types.rs [hunk 2]
```diff
@@ -249,23 +249,27 @@ impl<'a> ArgsIterator<'a> {
...
+            defaults[i] = Self::sql_to_graphql_default(default_strs[i - start_idx], arg_types[i])
         }
 
         defaults
     }
 
-    fn sql_to_graphql_default(default_str: &str, type_oid: u32) -> Option<String> {
+    fn sql_to_graphql_default(default_str: &str, type_oid: u32) -> Option<(String, bool)> {
         let trimmed = default_str.trim();
+        if trimmed.starts_with("NULL::") {
```
Comment (olirice) [inline src/sql_types.rs:260]: are you confident this is always reliable wrt uppercase/lowercase? Will it alway be cast with a `::`?

**Review by olirice — APPROVED** [review]

File: src/sql_types.rs (hunk 1 above)
Comment (imor) [reply src/sql_types.rs]: Agree, tuple was hard to read. Replaced with an enum.

File: src/sql_types.rs (hunk 2 above)
Comment (imor) [reply src/sql_types.rs:266]: > are you confident this is always reliable wrt uppercase/lowercase?

Yes, Postgres converts all cases into capitals. Added a test for this.

> Will it alway be cast with a ::?

A `<arg> <type> default null` form is always converted into a cast of the form `NULL::<type>`. Other, more complex forms of expressions might not work.

Comment (imor) [reply src/sql_types.rs:266]: Also updated docs with the caveat that only simple `default null` are supported for now.
